### PR TITLE
fix: Update DieHard build to use CMake and correct library path

### LINKED ISSUE #222: Fix DieHard build
It recently [moved to cmake](https://github.com/emeryberger/DieHard?tab=readme-ov-file#linux--mac):

```
 --------------------------------------------
build dh: version master
--------------------------------------------

~/work/mimalloc-bench/mimalloc-bench/extern ~/work/mimalloc-bench/mimalloc-bench
Cloning into 'dh'...
Already on 'master'
Your branch is up to date with 'origin/master'.
make: *** No rule to make target 'linux-gcc-64'.  Stop.
make: Entering directory '/home/runner/work/mimalloc-bench/mimalloc-bench/extern/dh/src'
make: Leaving directory '/home/runner/work/mimalloc-bench/mimalloc-bench/extern/dh/src'
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by XueSongTap**
fix: Update DieHard build to use CMake and correct library path

- Replace Makefile-based build with CMake (matches upstream)
- Fix library path from src/libdieharder.so to src/build/libdieharder.so
- Remove directory stack manipulation to fix popd error

Fixes #222

self test:
```
yxc@yxc-MS-7B89:~/code/2505/mimalloc-bench_dev$ ./build-bench-env.sh bench dh

building with 16 threads
--------------------------------------------
--------------------------------------------
build dh: version master
--------------------------------------------
~/code/2505/mimalloc-bench_dev/extern ~/code/2505/mimalloc-bench_dev
Cloning into 'dh'...
remote: Enumerating objects: 3091, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 3091 (delta 60), reused 66 (delta 30), pack-reused 2974 (from 1)
Receiving objects: 100% (3091/3091), 38.56 MiB | 7.66 MiB/s, done.
Resolving deltas: 100% (1338/1338), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
[100%] Linking C executable espresso
[100%] Built target espresso


--------------------------------------------
installed allocators
--------------------------------------------

dh:   master,  975a067,   https://github.com/emeryberger/DieHard
lua:  v5.4.7,  1ab3208a,  https://github.com/lua/lua

--------------------------------------------
done in /home/yxc/code/2505/mimalloc-bench_dev
--------------------------------------------

run the cfrac benchmarks as:
> cd out/bench
> ../../bench.sh alla cfrac

to see all options use:
> ../../bench.sh help
yxc@yxc-MS-7B89:~/code/2505/mimalloc-bench_dev$ cd out/bench
yxc@yxc-MS-7B89:~/code/2505/mimalloc-bench_dev/out/bench$ ../../bench.sh alla cfrac
benchmarking on 16 cores.
use '-h' or '--help' for help on configuration options.

allocators:  sys dh
tests     :  cfrac
(excluded tests:  lean lean-mathlib)

---- 1: cfrac

run 1: cfrac sys: SYSMALLOC=1 ./cfrac 17545186520507317056371138836327483792789528
cfrac       sys   0:06.29 2900 6.28 0.00 0 424

run 1: cfrac dh: LD_PRELOAD=/home/yxc/code/2505/mimalloc-bench_dev/extern/dh/src/build/libdieharder.so ./cfrac 17545186520507317056371138836327483792789528
cfrac       dh    0:12.25 9496 12.24 0.00 0 1384

results written to: /home/yxc/code/2505/mimalloc-bench_dev/out/bench/benchres.csv

#------------------------------------------------------------------
# test    alloc   time  rss    user  sys  page-faults page-reclaims
cfrac       sys   06.29 2900 6.28 0.00 0 424
cfrac       dh    12.25 9496 12.24 0.00 0 1384

```

### CODE REVIEW

File: build-bench-env.sh [hunk 1]
```diff
@@ -565,11 +565,12 @@ if test "$setup_dh" = "1"; then
...
-  if test "$darwin" = "1"; then
-    TARGET=libdieharder make -C src macos
-  else
-    TARGET=libdieharder make -C src linux-gcc-64
-  fi
+  cd src
+  mkdir -p build
+  cd build
+  cmake ..
+  make
```
Comment (jvoisin) [inline build-bench-env.sh:572]:
```suggestion
  cmake -S . -B build
  cmake --build build -j `nproc`
```

I think this is how it's done with modern cmake
